### ISSUE TITLE
net-misc/cjdns deleted?

### ISSUE THREAD

**Issue by CocolinoFan** [Weuxel/portage-weuxel#8]
Hello sir,
I am unable to install cjdns anymore, at least not trough Gentoo's eselect repository. I was able to add your repository but, `emerge net-misc/cjdns` does not find the package. 
I found [this](https://github.com/Weuxel/portage-weuxel/commit/dec4d904bc046236135eeee9c6f3e2d36ebe72a9) commit titled "cjdns deleted", are you not maintaining it anymore?

**Comment by Weuxel** [comment]
Hello,
as the project became kind of stale and the community seemed to disappear, i stopped my engagement in the project.
So i am not maintaining this package in my repo any more and deleted it as it would not build eventually.

**Comment by CocolinoFan** [comment]
Sad times, but I understand. Thank you for maintaining it so far sir, it was really nice to installing it through portage.
